# Generated by Django 6.1 on 2026-09-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('plazo_dias', models.PositiveIntegerField(default=1)),
                ('gratuito', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('con restricciones', 'Con restricciones'), ('no disponible', 'No disponible')], default='disponible', max_length=30)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
